apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "{{ prom_port }}"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: jvkhan/fluentd:v1.4-kafka
        imagePullPolicy: Always
        env:
          - name: FLUENTD_PROMETHEUS_PORT
            value: "{{ prom_port }}"
          - name: FLUENTD_PROMETHEUS_PATH
            value: "/api/v1/metrics/prometheus"
          - name:  CLUSTER
            value: "{{ cluster_name }}"
          - name:  FLUENT_KAFKA_DEFAULT_TOPIC
            value: "{{ cluster_name }}-fluentd"
          - name:  FLUENT_KAFKA_BROKERS 
            value: "{{ fluentd_kafka_brokers }}"
        resources:
          limits:
            memory: {{ fluentd_memory_limit | default("1G")  }}
          requests:
            cpu: 500m
            memory: 1G
        ports:
        - containerPort: 9880
          name: http-input
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            # Using percent encoding for query param: {"log": "health check"}
            # curl -X POST -d 'json={"log":"health check"}' "http://<fluentd-serviceIP>:9880" /fluentd.pod.healthcheck
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - mountPath: /fluentd/etc/kubernetes.conf
          name: fluent-config-kube
          subPath: kubernetes.conf
        - mountPath: /fluentd/etc/fluent.conf
          name: fluent-config
          subPath: fluent.conf
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: internalpull
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-config
        name: fluent-config
      - configMap:
          defaultMode: 420
          name: fluentd-config-kube
        name: fluent-config-kube
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
     # use correct journald log path for your nodes here
      - name: journal
        hostPath:
          path: /run/log/journal

