apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-logging
  ports:
     - name: http-input
       port: 9880
       targetPort: http-input
       protocol: TCP

